Vagrant.configure("2") do |config|
    config.vagrant.plugins = ["vagrant-vbguest"]
    
    config.vm.box = "centos/8"
    config.vm.box_version = "1905.1"
    config.vm.network "private_network", ip: "192.168.20.10"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
    end
    
    # config.vm.provision "ansible" do |ansible|
    #     # ansible.inventory_path = "ansible/gst-inventory"
    #     ansible.playbook = "ansible/install_node_exporter.yaml"
    # end
end