---
- hosts: all
  become: true
  tasks:
  - name: Create Node Exporter user group
    become: true
    group:
      name: node_exporter
      state: present

  - name: Create Node Exporter user
    become: true
    user:
      name: node_exporter
      shell: /sbin/nologin
      group: node_exporter
      state: present

  - name: Create textfile collector home dir
    file:
      path: /var/lib/node_exporter
      state: directory
      owner: node_exporter
      group: node_exporter

  - name: Write config file
    become: true
    lineinfile:
      dest: /etc/sysconfig/node_exporter
      line: OPTIONS="--collector.textfile.directory /var/lib/node_exporter/textfile_collector"
      state: present
      create: yes

  - name: download tar file
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tar.gz

  - name: Create node_exporter bin home
    file: 
      path: /usr/share/node_exporter
      state: directory

  - name: extract tar
    become: true
    unarchive:
      src: /tmp/node_exporter.tar.gz
      dest: /usr/share/node_exporter
      creates: /usr/share/node_exporter/node_exporter-1.0.1.linux-amd64
      remote_src: yes
      owner: node_exporter

  - name: Setup systemd node_exporter service
    become: true
    shell: |
      tee -a /etc/systemd/system/node_exporter.service << END
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=node_exporter
      EnvironmentFile=/etc/sysconfig/node_exporter
      ExecStart=/usr/share/node_exporter/node_exporter-1.0.1.linux-amd64/node_exporter \$OPTIONS
      [Install]
      WantedBy=multi-user.target
      END

  - name: Start node_exporter service
    become: true
    shell: |
      systemctl daemon-reload
      systemctl enable node_exporter
      systemctl start node_exporter
